// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static bool get isConfigured =>
      android.appId != 'YOUR_APP_ID' &&
      android.apiKey != 'YOUR_API_KEY' &&
      android.projectId != 'YOUR_PROJECT_ID';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiYiSrCUNOXa3OBUSrsLA8wFsAXOC76y0',
    appId: '1:382659412362:android:95775f621567a215804873',
    messagingSenderId: '382659412362',
    projectId: 'quran-glow',
    storageBucket: 'quran-glow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFaA6QuGPpBwcxIC9hcM5S-PEGFlGX4ac',
    appId: '1:382659412362:ios:5fe904b618102223804873',
    messagingSenderId: '382659412362',
    projectId: 'quran-glow',
    storageBucket: 'quran-glow.firebasestorage.app',
    iosBundleId: 'com.example.quranglow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFaA6QuGPpBwcxIC9hcM5S-PEGFlGX4ac',
    appId: '1:382659412362:ios:5fe904b618102223804873',
    messagingSenderId: '382659412362',
    projectId: 'quran-glow',
    storageBucket: 'quran-glow.firebasestorage.app',
    iosBundleId: 'com.example.quranglow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyaAJxDhuOUnusybeGXVd-_CNXURXqAT8',
    appId: '1:382659412362:web:aaafb3d4917a630e804873',
    messagingSenderId: '382659412362',
    projectId: 'quran-glow',
    authDomain: 'quran-glow.firebaseapp.com',
    storageBucket: 'quran-glow.firebasestorage.app',
    measurementId: 'G-J5CP8J49YF',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyaAJxDhuOUnusybeGXVd-_CNXURXqAT8',
    appId: '1:382659412362:web:e884140da2092469804873',
    messagingSenderId: '382659412362',
    projectId: 'quran-glow',
    authDomain: 'quran-glow.firebaseapp.com',
    storageBucket: 'quran-glow.firebasestorage.app',
    measurementId: 'G-23SNLDMV41',
  );

}