name: quranglow
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  rename: ^3.1.0
  http: ^1.5.0
  just_audio: ^0.10.5
  path_provider: ^2.1.5
  flutter_riverpod: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.9.0
  connectivity_plus: ^7.0.0
  shared_preferences: ^2.5.3
  state_notifier: ^1.0.0
  google_fonts: ^6.3.2
  lottie: ^3.3.2
  wakelock_plus: ^1.4.0
  riverpod: ^3.0.1
  just_audio_windows: ^0.2.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  analyzer: ^6.4.1
  flutter_native_splash: ^2.2.11

flutter:
  uses-material-design: true

  assets:
    - assets/anim/Quran.json
    - assets/iosn/icongrowquran.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/iosn/icongrowquran.jpg"
  adaptive_icon_background: "#FFFFFF"

flutter_native_splash:
  color: "#FFFFFF"       
  color_dark: "#121212"  
  android_12:
    color: "#FFFFFF"
    color_dark: "#121212"
